name: Branch Protection

on:
  push:
    branches:
      - main
      - 'release/**'

  pull_request:
    branches:
      - main
      - 'release/**'

jobs:
  protect:
    runs-on: ubuntu-latest

    steps:
      - name: Check if push to main or release branch
        if: |
          github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/'))
        run: |
          echo "Direct pushes to ${{ github.ref }} branch are not allowed. Please create a pull request instead."
          exit 1

      - name: Check if pull request targets main or release branch
        if: |
          github.event_name == 'pull_request' && github.event.action == 'opened' &&
          (github.event.pull_request.base.ref == 'main' || startsWith(github.event.pull_request.base.ref, 'release/'))
        run: |
          echo "Pull requests directly targeting ${{ github.event.pull_request.base.ref }} branch are not allowed."
          exit 1